# Generated by Django 4.0.3 on 2022-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
