# Generated by Django 4.0.3 on 2022-03-30 18:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 30, 18, 7, 42, 117609, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
